# Generated by Django 4.1.5 on 2023-01-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='numbers',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
